### ISSUE TITLE
Allow for non-Android devices

### ISSUE THREAD

**Issue by jromero2k** [wideverse/headless-wifi-manager#2]
This would be awesome for use in other headless devices, like Raspberry Pis and clones.

Maybe someone with Linux knowledge could adapt this for such cases?

Thanks anyways. Great work!

**Comment by lopsandrea** [comment]
Hello! Thank you
Our library is designed for android devices, and specifically uses the Nearby API to do this. Linux support has not really been thought for the moment!

**Comment by dpnkrg** [comment]
Hello, any update or this side. I am waiting for the headless raspberry pi setup. Any idea or update?
How can I implement this?
